### ISSUE TITLE
🐛Bug: Is the Dialog component missing an openChange attribute as compared to the Dialog in radix ui ?

### ISSUE THREAD

**Issue by PintoGideon** [radix-svelte/radix-svelte#172] opened 2023-06-30 14:41 UTC
Radix UI exposes an `onOpenChange` function on it's Dialog.Root component which makes it easy for the user to control the Dialog based on custom logic.

For example, I would like to do something like this.

```
<script>

let isOpen=true;

function setIsOpen () {

//custom logic


isOpen= !isOpen


}

</script>


<Dialog.Root open={open} onOpenChange{setOpen}/>

```
Is there a reason why this function is not exposed in radix-svelte. I see the open and modal attribute exposed.

**Comment by TGlide** [comment] 2023-06-30 20:24
We don't expose change functions because in Svelte you have two-way bindings + reactive statements, which should fulfill these use cases.

Closing since this is not a bug, but if you feel this would be a worthwhile addition, feel free to open a feature request. Please note though that Radix Svelte is not under active development.

**Closed** 2023-06-30 20:24 UTC
Labels: bug

**Comment by PintoGideon** [comment] 2023-06-30 20:42
@TGlide 

Quick question if you don't mind. Is there a way to know when the dialog was closed so I can do a cleanup.

For example:

```javascript

{#if preview}
  <Dialog open={true} modal={true}>
    <DialogContent
      class="w-full h-full"
    >
      <FilePreview {fileToPreview}  />
    </DialogContent>
  </Dialog>
{/if}
```

Is there a way to know when the Dialog was closed by passing down a callback like this
`
<DialogContent on:close={()=>console.log('closed')}/>`

**Comment by TGlide** [comment] 2023-06-30 22:09
You can bind to the open value and listen to it that way.

E.g.
```
let open = false

$: if (!open) console.log("closed")

<Dialog.Root bind:open />
```

**Comment by PintoGideon** [comment] 2023-06-30 22:23
@TGlide  Thanks a lot. Just migrating over to svelte from the react world so I am lacking some creativity. Also, Melt UI looks awesome. Grateful for the work you do.

**Comment by TGlide** [comment] 2023-06-30 22:31
> @TGlide  Thanks a lot. Just migrating over to svelte from the react world so I am lacking some creativity. Also, Melt UI looks awesome. Grateful for the work you do.
> 

Thank you for your kind words! In Melt this would be generally easier tbh, as we expose the open variable as a store by default, allowing you to use subscribe on it.
